services:
  - type: web
    name: velox-backend
    env: docker
    plan: free
    dockerContext: .
    dockerfilePath: Dockerfile
    healthCheckPath: /
    envVars:
      - key: STRIPE_SECRET_KEY
        sync: false
      - key: OPENAI_API_KEY
        sync: false
      - key: API_KEY
        value: proxima-key-2026
